### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [pmarchand1/waver#2]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

`waver` depends/imports 'rgdal', 'rgeos' rgeos::gBinarySTRtreeQuery rgeos::gDistance rgeos::gIntersection rgeos::gIntersects rgeos::gUnaryUnion, of which rgeos::gBinarySTRtreeQuery has no continuation - all `sf` topological predicates and operations use indexing anyway. Please see https://r-spatial.org/r/2023/04/10/evolution3.html and https://github.com/r-spatial/evolution/blob/main/pkgapi_230305_refs.csv for suitable mitigations. Please fix best by June, latest October 2023.

**Comment by pmarchand1** [comment]
Fixed in v0.3.0 now on CRAN
